---
# This routine executes provisioning of a single interface
#
# The Playbook is executed with all runtime variables passed to it, including the inventory: 
# ansible-playbook -i "10.1.1.1," NXOS-ansible-usercreate.yml --extra-vars="username=admin password=juju new_username=newadmin new_password=newPassw0rd user_role=network-admin"
#
# Note that the inventory is passed within "" and includes a trailing comma. The trailing comma is important
# as it differentiates a list of devices or hostname vs an inventory file. Also note the description where
# spaces can be processed within a variable
#
- name: Ansible Configure Access Interface Routine for NX-OS
  # Process all hosts provided in the inventory (list provided at runtime)
  hosts: all
  # Use the local Ansible system
  connection: local
  # Dont bother with fact computation about remote entities wont need that for the simple plays being run
  gather_facts: no

  # Use Username and Password provided at runtime combined with the hostname list (also passed as a variable)
  vars:
    nxos_provider:
      username: "{{ username }}"
      password: "{{ password }}"
      host: "{{ inventory_hostname }}"

  # Use the NX-OS User Ansible module to create a user, password, and role that is passed during runtime.
  tasks:
  - name: Configure User
    nxos_user:
      provider: "{{ nxos_provider }}"
      name: "{{ new_username }}"
      role: "{{ user_role }}"
      configured_password: "{{ new_password }}"